In [2]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/dataprofessor/data/refs/heads/master/delaney_solubility_with_descriptors.csv')
print(df.head(10))

   MolLogP    MolWt  NumRotatableBonds  AromaticProportion  logS
0   2.5954  167.850                0.0                 0.0 -2.18
1   2.3765  133.405                0.0                 0.0 -2.00
2   2.5938  167.850                1.0                 0.0 -1.74
3   2.0289  133.405                1.0                 0.0 -1.48
4   2.9189  187.375                1.0                 0.0 -3.04
5   1.8100   98.960                0.0                 0.0 -1.29
6   1.9352   96.944                0.0                 0.0 -1.64
7   1.4054  118.176                4.0                 0.0 -0.43
8   4.3002  215.894                0.0                 0.6 -4.57
9   2.5654  132.206                0.0                 0.6 -4.37

# Data Preparation

In [3]:
y = df['logS']
y

0      -2.180
1      -2.000
2      -1.740
3      -1.480
4      -3.040
        ...
1139    1.144
1140   -4.925
1141   -3.893
1142   -3.790
1143   -2.581
Name: logS, Length: 1144, dtype: float64

In [7]:
x = df.drop('logS', axis=1) #1 is for columns, 0 is for rows
x

      MolLogP    MolWt  NumRotatableBonds  AromaticProportion
0     2.59540  167.850                0.0            0.000000
1     2.37650  133.405                0.0            0.000000
2     2.59380  167.850                1.0            0.000000
3     2.02890  133.405                1.0            0.000000
4     2.91890  187.375                1.0            0.000000
...       ...      ...                ...                 ...
1139  1.98820  287.343                8.0            0.000000
1140  3.42130  286.114                2.0            0.333333
1141  3.60960  308.333                4.0            0.695652
1142  2.56214  354.815                3.0            0.521739
1143  2.02164  179.219                1.0            0.461538

[1144 rows x 4 columns]

Data splitting

In [9]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=100)

In [10]:
x_test

      MolLogP    MolWt  NumRotatableBonds  AromaticProportion
822   2.91000  172.268                7.0            0.000000
118   7.27400  360.882                1.0            0.666667
347   1.94040  145.161                0.0            0.909091
1123  1.98640  119.378                0.0            0.000000
924   1.70062  108.140                0.0            0.750000
...       ...      ...                ...                 ...
1114  1.76210  478.513                4.0            0.000000
427   6.32820  276.338                0.0            1.000000
711   0.04430  218.205                5.0            0.000000
4     2.91890  187.375                1.0            0.000000
948   3.56010  318.328                2.0            0.750000

[229 rows x 4 columns]

In [11]:
x_train

     MolLogP    MolWt  NumRotatableBonds  AromaticProportion
107  3.14280  112.216                5.0            0.000000
378 -2.07850  142.070                0.0            0.000000
529 -0.47730  168.152                0.0            0.000000
546 -0.86740  154.125                0.0            0.000000
320  1.62150  100.161                2.0            0.000000
..       ...      ...                ...                 ...
802  3.00254  250.301                1.0            0.842105
53   2.13860   82.146                3.0            0.000000
350  5.76304  256.348                0.0            0.900000
79   3.89960  186.339               10.0            0.000000
792  2.52334  310.297                3.0            0.300000

[915 rows x 4 columns]

Model Building

Linear Regression

In [16]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(x_train, y_train)

LinearRegression()

In [18]:
# Applying the model to make the predictions
y_lr_train_pred = lr.predict(x_train)
y_lr_test_pred = lr.predict(x_test)

y_lr_test_pred

array([-3.05722870e+00, -7.77785827e+00, -2.55016650e+00, -2.01523582e+00,
       -2.06375990e+00, -9.99672215e-01, -5.94603364e-01, -5.53626003e-01,
       -5.72200956e+00, -3.94006681e+00, -3.95496755e+00, -2.29737009e+00,
       -1.48980354e+00, -1.48988982e+00, -4.64510806e+00, -1.90396018e+00,
       -1.51566313e+00, -3.16424605e+00, -3.70863920e+00, -5.58105660e+00,
       -3.25038467e+00, -5.04235077e+00, -5.69194881e+00, -2.14339849e+00,
       -4.35689341e+00, -5.03964756e+00, -3.10383618e+00, -4.40286964e+00,
       -4.21276272e+00,  5.56508349e-01, -1.45537678e+00, -4.41027396e+00,
       -2.59668773e+00, -1.53336276e+00, -5.55749874e-01, -1.67111795e+00,
       -2.78163675e+00, -3.15395565e+00, -5.27083361e+00, -1.75321446e+00,
       -1.53350725e+00, -2.01255666e+00, -6.57559167e+00, -7.89433046e+00,
       -5.76437127e+00, -4.16422068e+00, -3.43694663e+00,  1.43834212e+00,
       -1.12679105e-02, -2.34521849e+00, -1.86480046e+00, -5.03964756e+00,
        8.55886378e-01, -3.17679292e+00, -5.06764094e+00, -1.99464442e+00,
       -7.77785827e+00, -1.21764693e+00, -9.09541075e-01, -5.04235077e+00,
       -2.43898748e+00, -2.84034045e+00, -2.53403538e+00, -2.36170311e+00,
       -1.63103729e+00, -1.53182046e+00, -3.23931568e+00, -2.88008616e+00,
       -1.88300518e+00, -3.21582220e+00, -3.40245202e+00, -9.01813905e-01,
       -4.82308940e+00, -7.69116343e-01, -7.12894308e+00, -1.05440427e+01,
       -1.95444152e+00, -3.50194744e+00, -7.18167736e+00, -6.01555673e+00,
       -2.08189806e+00, -2.31652280e+00, -3.44556948e+00, -2.05480142e+00,
       -6.01555673e+00, -2.88308299e+00, -4.84867198e+00, -3.51006495e-01,
       -3.54726250e+00, -1.21057919e+00, -4.36658559e+00, -4.21815903e-01,
       -1.63103729e+00, -2.51604291e+00, -2.16707077e+00, -1.48726025e+00,
       -3.20864450e+00, -1.51411141e+00, -1.65033691e+00, -3.66287663e+00,
       -3.26968347e+00, -3.94492313e+00, -4.22509088e+00, -3.68794650e+00,
       -5.98734972e+00, -1.43710934e+00, -1.97653920e+00, -1.85076729e+00,
       -1.14179382e+00, -3.07730828e+00, -4.84867198e+00, -2.19679345e+00,
       -1.68737438e+00, -2.20390218e+00,  1.89408269e+00, -3.61322115e+00,
       -2.79173430e+00, -2.41564138e+00, -7.53910534e-01, -8.54744860e-01,
       -9.20407401e-02, -6.14209981e+00, -3.79386016e+00, -7.77785827e+00,
       -1.79874130e+00, -2.50544035e+00, -3.77102985e+00, -2.25250766e+00,
       -2.57788713e+00, -2.06375990e+00, -3.33843958e+00, -1.03912484e+00,
       -6.68946164e+00, -1.91112045e+00, -2.58735850e+00, -2.19902800e+00,
       -1.90219551e+00, -2.81396751e+00, -4.16972153e+00, -5.72200956e+00,
       -1.60816482e+00, -3.68121117e+00, -4.60929775e+00, -2.45888480e+00,
        1.13185484e+00, -1.69279625e+00, -7.09025955e+00, -3.79386016e+00,
       -2.99712058e+00, -5.79600137e+00, -2.44845780e+00, -5.29399242e+00,
       -5.29389899e-01, -3.53652118e+00, -3.51200413e+00, -2.02419300e+00,
       -4.47466933e+00, -3.63836536e+00, -4.56596939e+00, -5.57842703e+00,
       -5.30676136e+00, -2.39225449e+00, -4.88290144e+00, -2.61359308e+00,
       -3.11841945e+00, -2.05580278e+00, -1.64987419e+00, -4.91881901e+00,
       -3.93774254e+00, -4.26411548e+00, -3.15082845e+00, -3.49352203e+00,
       -3.81768831e+00, -3.77197350e+00, -2.55016650e+00, -1.97653920e+00,
       -2.59432621e+00, -5.38480406e+00, -5.44932525e+00, -3.04107137e+00,
       -1.87252408e+00, -2.25124657e+00, -2.89215707e+00, -3.46087334e+00,
       -6.06861986e+00, -1.89916369e+00, -1.98035105e+00, -2.45036038e+00,
       -2.79393037e+00, -4.76010415e+00, -1.72379306e+00, -7.09025955e+00,
       -2.86880150e+00, -2.70674744e+00, -4.36825704e+00, -3.11841945e+00,
       -3.85805633e+00,  9.78662246e-03, -4.47466933e+00, -6.08708502e+00,
       -5.19970454e+00, -6.40483191e+00, -4.10155218e+00, -1.07044752e+00,
        1.99249372e+00, -3.63698515e+00, -8.50933009e-01, -3.26770298e+00,
       -4.78343575e+00, -1.48988982e+00, -2.24629276e+00, -4.13247222e+00,
       -4.36873484e+00, -1.89724815e+00, -1.50596465e+00, -1.16713539e-02,
       -1.73602998e+00, -2.34521849e+00, -4.54942814e-01, -4.18812419e+00,
       -1.87770440e+00, -3.70838271e+00, -1.59899899e+00, -3.26143822e+00,
       -4.17623614e+00, -6.67872053e+00, -1.23069039e+00, -3.14545964e+00,
       -4.79863925e+00])

In [25]:
# Evaluate the model performance

from sklearn.metrics import mean_squared_error, r2_score

lr_train_mse = mean_squared_error(y_train, y_lr_train_pred)
lr_train_r2 = r2_score(y_train, y_lr_train_pred)

lr_test_mse = mean_squared_error(y_test, y_lr_test_pred)
lr_test_r2 = r2_score(y_test, y_lr_test_pred)

In [26]:
print('Linear Regression Train MSE:', lr_train_mse)
print('Linear Regression Train R2:', lr_train_r2)
print('Linear Regression Test MSE:', lr_test_mse)
print('Linear Regression Test R2:', lr_test_r2)

Linear Regression Train MSE: 1.0075362951093687
Linear Regression Train R2: 0.7645051774663391
Linear Regression Test MSE: 1.0206953660861033
Linear Regression Test R2: 0.7891616188563282

In [27]:
lr_results = pd.DataFrame({'Model': ['Linear Regression'],
                           'Train MSE': [lr_train_mse],
                           'Train R2': [lr_train_r2],
                           'Test MSE': [lr_test_mse],
                           'Test R2': [lr_test_r2]})
lr_results

               Model  Train MSE  Train R2  Test MSE   Test R2
0  Linear Regression   1.007536  0.764505  1.020695  0.789162